### ISSUE TITLE
Change beam interp code to accomodate pyuvsim 1.2.5

### ISSUE THREAD

**Issue by jburba** [HydraRadio/Hydra#2]
The latest pyuvsim fixes a big when Nsky_parts > 1 where only a part of the sky was being simulated.  This update changes the axes of the beam interpolation function in the AnalyticBeam class (likely to jive with a newer version of pyuvdata and potentially the removal of the Nspws axis).  The new number of axes for the interpolation products is 4 (as opposed to 5 in pyuvsim <= 1.2.4).

**Comment by mwilensky768** [comment]
Resolved by #3
